### ISSUE TITLE
Ability to surpress warnings of vehicle making no money. By vehicle.

### ISSUE THREAD

**Issue by barbary** [voxeltycoon/suggestions#127] opened 2020-04-21 13:50 UTC
Add a tick box when setting up a vehicle that will mean I never get warned if this vehicle makes no money.

I have many trains that move goods between stations to then be distributed by cars/trucks. These trains will never make money and each month I get a warning for each of them to tell me it didn't make money.

**Comment by andrewpey** [comment] 2020-04-21 15:25
This is strange because this warning actually checks for cargo transferred by the vehicle. If no cargo was transferred for the last 30 days, the warning is shown.

- What's the version of the game where this issue could be found?
- Do your vehicles transfer items rarer than every 30 days?
- If no, do you have a save where we can reproduce this issue?

**Comment by barbary** [comment] 2020-04-21 21:29
With the extra info I can confirm that many of them transfer goods less than every 30 days.  I have chosen to use very large trains that need to travel infrequently. It might still be useful but I do see that once my towns people start demanding higher end goods maybe more of the messages will go away.

**Comment by andrewpey** [comment] 2020-04-22 18:21
Thanks for letting us know this is working as intended.

We plan to add more options to control notifications in the future.

**Closed by andrewpey** 2020-04-22 18:21 UTC

**Comment by andrewpey** [comment] 2020-05-18 19:20
By the way, we've added option to mute this notification per vehicle in `0.83` under three dots menu:
![image](https://user-images.githubusercontent.com/1748681/82251336-abb11300-9955-11ea-88b4-37b783e8564b.png)
