### ISSUE TITLE
Station name suffixes in Japanese

### ISSUE THREAD

**Issue by alt168** [voxeltycoon/suggestions#200] opened 2021-04-17 18:33 UTC
In Japanese, "駅(Eki/station)" refers only to railroad stations and is not used for road stations.
So, I think it is more natural not to add "駅" as a suffix to both railroad and road stations, should just be directions.

**Comment by victorleblais** [comment] 2021-04-21 10:21
Duplicate of #61

**Closed by victorleblais** 2021-04-21 10:21 UTC
Labels: i18n
