### ISSUE TITLE
More city control

### ISSUE THREAD

**Issue by esteemdav** [voxeltycoon/suggestions#151] opened 2021-01-13 13:12 UTC
so every now and then a city expands. It would be nice if there was a checkmark that would indicate whether or not you want to place the next queued thing yourself or auto-place them as the in-game system does.

it:
- raises optional difficulty
- gives the tinkerers some love when designing a city to look nice (potentially good with mods)
- by manually designing your cities it could provide a useful tool for population control for the passenger transportation that you've got in your pipeline somewhere

**Comment by andrewpey** [comment] 2021-01-13 17:08
Is not this duplicate of #150?

**Comment by esteemdav** [comment] 2021-01-13 17:16
> Is not this duplicate of #150?

yeah you're right I guess I done some oopsie...

**Comment by andrewpey** [comment] 2021-01-13 17:16
No problem!

**Closed** 2021-01-13 17:16 UTC
